### ISSUE TITLE
Case insensitive parser

### ISSUE THREAD

**Issue by Keyamoon** [elm-community/parser-combinators#26]
Perhaps I'm missing something, but I didn't find any way to make a case insensitive string/regex parser.

**Comment by stil4m** [comment]
@Keyamoon Currently that is not supported.
The library compiles its [own regex](https://github.com/elm-community/parser-combinators/blob/cd1fb001ce7632f32e5bcbc6689f081984c9f916/src/Combine.elm#L711) and it does this to control the fact that the regex only has to match the [beginning of the input](https://github.com/elm-community/parser-combinators/blob/cd1fb001ce7632f32e5bcbc6689f081984c9f916/src/Combine.elm#L707).

The result is that simply passing in a `Regex` that is case insensitive is not an option, because the package will lose the control it needs. The current workaround is to use the `regex` function in this package with regexes having case insensitive character classes. For example: `[A-Za-z]` or `[A-z]`.

The `string` is case insensitive by design. Using an `or` (`or (string "foo") (string "FOO")`) or `choice` may help you in this.

Does this work for you?

Otherwise, can you state what you try to achieve with and provide a real example?

**Comment by Keyamoon** [comment]
I think you meant to say that `string` is case <em>sensitive</em> by design.

I'm trying to parse an HTML doctype declaration. I'm currently using an `or` for parsing "doctype" or "DOCTYPE", but something like "docTyPe" would be valid too.

**Comment by Keyamoon** [comment]
Just realized I could use `[dD][oO][cC][tT][yY][pP][eE]` too.

**Comment by stil4m** [comment]
Yes I meant to say sensitive.

The 'ugly' but working solution for now would be a regex that matches each char case insensitive:

```
(d|D)(o|O)(c|C) ...
```

But this is suboptimal.

Adding one or two new functions would be an option `regexWithOptions` and/or `caseInsensitiveString`, but I would like more feedback from other people before adding these parsers.

**Comment by stil4m** [comment]
@Keyamoon When you only encounter this in the doctype string, I think this is a good workaround.

In addition: Maybe look into [elm-xml](http://package.elm-lang.org/packages/eeue56/elm-xml/2.2.2/Xml#Value). This library may contain what you are trying to do.

**Comment by Keyamoon** [comment]
Yeah, it's a good workaround for now. Thank you.

It's definitely better to get more feedback before jumping to conclusion and adding new functions.

**Comment by stil4m** [comment]
I'll leave the issue open for now. I'll check back in after a while.

**Comment by stil4m** [comment]
Will close due to inactivity
